## Spring Boot App
apiVersion: apps/v1
kind: Deployment
metadata:
  name: NginxImage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
    spec:
      containers:
      - name: nginx
        image: 8574122/nginximage
        ports:
        - containerPort: 8080
        
