
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: nginx
  name: spring-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx
    spec:
      imagePullSecrets:
      - name: dockerreposecret
      containers:
      - image: 8574122/nginximage
        name: nginx
        ports:
        - name: nginx
          containerPort: 8080      
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx
  name: nginx
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: nginx
